version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "16686:16686"
      - "14268:14268"

  # Collector
  oc-collector:
    image: omnition/opencensus-collector:0.1.10
    command: ["/occollector_linux", "--config=/etc/oc-collector-config.yaml"]
    volumes:
      - ./oc-collector-config.yaml:/etc/oc-collector-config.yaml
    ports:
      - "55678:55678"
    depends_on:
      - jaeger-all-in-one
